# Generated by Django 5.0.7 on 2024-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
