# Generated by Django 5.0.7 on 2024-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_app',
            name='api_key',
            field=models.TextField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
