# Generated by Django 5.0.7 on 2024-08-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_auth', '0001_initial'),
        ('user_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validate', models.BooleanField(default=False)),
                ('prompt', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_apps.user_app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_auth.newuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
