# Generated by Django 5.0.7 on 2024-08-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_auth', '0001_initial'),
        ('user_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='validators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descriptions', models.TextField()),
                ('parameters', models.JSONField()),
                ('codename', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Associated_validators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apikey', models.TextField()),
                ('parameters', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_auth.newuser')),
                ('userapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_apps.user_app')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validators.validators')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
