# Generated by Django 5.0.7 on 2024-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated_validators',
            name='apikey',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='validators',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
